name: Publish

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v6

      - name: Setup Deno
        uses: denoland/setup-deno@v2 # v2.0.3

      - name: Verify formatting
        run: deno fmt --check

      - name: Run linter
        run: deno lint

      - name: Run tests
        run: deno task unit_test
  release:
    permissions:
      contents: write

    if: startsWith(github.ref, 'refs/tags/v')
    needs:
      - test

    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v6

      - name: Setup Deno
        uses: denoland/setup-deno@v2 # v2.0.3
      - uses: actions/checkout@v6
      - run: deno task publish-openvsx --pat ${{ secrets.OVSX_TOKEN }}
      - run: deno task publish --pat ${{ secrets.VSCE_TOKEN }}
      - uses: softprops/action-gh-release@v2
        with:
          draft: true
