name: Publish

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v6

      - name: Setup Deno
        uses: denoland/setup-deno@v2 # v2.0.3

      - name: Verify formatting
        run: deno fmt --check

      - name: Run linter
        run: deno lint

      - name: Run tests
        run: deno task unit_test

  release:
    permissions:
      contents: write
      id-token: write # required for OIDC token exchange

    if: startsWith(github.ref, 'refs/tags/v')
    needs:
      - test

    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v6
      - uses: taiki-e/create-gh-release-action@f67cf7b2dadd83d36b981e674a6b08063997ce68 # v1.10.0
        with:
          branch: master
          changelog: CHANGELOG.md
          draft: true
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Deno
        uses: denoland/setup-deno@v2 # v2.0.3
      - uses: actions/checkout@v6
      - run: deno task publish-openvsx --pat ${{ secrets.OVSX_TOKEN }}
      - run: deno task publish --pat ${{ secrets.VSCE_TOKEN }}
      - name: Publish github release
        run: |
          if [[ $(echo "${GTIHUB_REF#refs/tags/v}" | grep '-' > /dev/null) ]]; then
            gh release edit "${GITHUB_REF#refs/tags/}" --prerelease
          fi
          gh release edit "${GITHUB_REF#refs/tags/}" --draft=false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
