name: Publish

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: "22.x"
      - uses: pnpm/setup@v2
        with:
          version: 11
          runtime: node@22
          cache: true
      - run: corepack pnpm install
      - run: corepack pnpm fmt:check
      - run: corepack pnpm test

  release:
    permissions:
      contents: write
      id-token: write

    if: startsWith(github.ref, 'refs/tags/v')
    needs:
      - test

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - uses: actions/setup-node@v7
        with:
          node-version: "22.x"
      - uses: pnpm/setup@v2
        with:
          version: 11
          runtime: node@22
          cache: true
      - run: corepack pnpm install
      - run: corepack pnpm build
      - run: corepack pnpm ovsx publish -p ${{ secrets.OVSX_TOKEN }} --no-dependencies
      - run: corepack pnpm vsce publish -p ${{ secrets.VSCE_TOKEN }} --no-dependencies
      - uses: taiki-e/create-gh-release-action@eba8ea96c86cca8a37f1b56e94b4d13301fba651 # v1.11.0
        with:
            branch: main
            changelog: CHANGELOG.md
            draft: true
            token: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish github release
        run: |
          if [[ $(echo "${GTIHUB_REF#refs/tags/v}" | grep '-' > /dev/null) ]]; then
            gh release edit "${GITHUB_REF#refs/tags/}" --prerelease
          fi
          gh release edit "${GITHUB_REF#refs/tags/}" --draft=false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
